params:
  epochs: 5
  batch_size: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000



artifacts: 
  artifacts_dir: artifacts
  model_dir: model
  ckpt_model_dir: ckpt_model
  ckpt_model_name: ckpt.h5
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plots_name: mnist

logs:
  logs_dir: logs
  general_logs: general_logs
  general_logs_name: general_logs.log
  tensorboard_logs: tensorboard_logs
  tensorboard_name: tensorboard